"""empty message

Revision ID: de7f7d76afb0
Revises: d447664b17a6
Create Date: 2017-06-06 11:37:56.154916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7f7d76afb0'
down_revision = 'd447664b17a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('bucketlist_id', sa.Integer(), nullable=True))
    op.drop_constraint('item_list_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'bucketlist', ['bucketlist_id'], ['id'])
    op.drop_column('item', 'list_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_list_id_fkey', 'item', 'bucketlist', ['list_id'], ['id'])
    op.drop_column('item', 'bucketlist_id')
    # ### end Alembic commands ###
